project:
  type: book 
  output-dir: docs


book:
  title: "SS time crystals"
  author: "Sebastián Torres"
  date: "25/3/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand




